# Generated by Django 4.0.3 on 2022-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.TextField(default='')),
                ('fname', models.TextField(default='')),
                ('mname', models.TextField(default='')),
                ('sname', models.TextField(default='')),
                ('bdate', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('contactno', models.TextField(default='')),
                ('status', models.TextField(default='pending')),
            ],
        ),
    ]
