# Generated by Django 4.0.3 on 2022-06-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nidsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
